name: CI
on: [push, pull_request]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "仓库已经拉下来了"
      - run: ls -la
      - run: python -c "print('hello CI')"
